# Generated by Django 5.2 on 2025-04-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=255)),
                ("original_price", models.FloatField()),
                ("discount_price", models.FloatField()),
                (
                    "discount_startdate",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
                (
                    "discount_enddate",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
                ("maker", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_type", models.CharField(max_length=100)),
                ("game_image_url", models.URLField(blank=True, null=True)),
                ("game_url", models.URLField(blank=True, null=True)),
                (
                    "collect_date",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_name",
                    models.CharField(default="", max_length=50, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="", max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.genre"
                    ),
                ),
            ],
            options={
                "db_table": "games_genres",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="genre",
            field=models.ManyToManyField(through="games.GameGenre", to="games.genre"),
        ),
        migrations.CreateModel(
            name="GameLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.language"
                    ),
                ),
            ],
            options={
                "db_table": "games_languages",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="game_language",
            field=models.ManyToManyField(
                through="games.GameLanguage", to="games.language"
            ),
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
