# Generated by Django 5.2 on 2025-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_startdate', models.DateField(blank=True, null=True)),
                ('discount_enddate', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('maker', models.CharField(max_length=100)),
                ('player_number', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=100)),
                ('game_language', models.CharField(max_length=100)),
                ('game_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
