# Generated by Django 5.2 on 2025-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="collect_date",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
