# Generated by Django 5.2 on 2025-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_collect_date_alter_game_discount_enddate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="player_number",
            new_name="play_number",
        ),
    ]
