# Generated by Django 5.2 on 2025-04-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False},
        ),
    ]
