# Generated by Django 5.2 on 2025-04-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_rename_player_number_game_play_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="play_number",
            new_name="player_number",
        ),
    ]
