# Generated by Django 5.2 on 2025-04-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
    ]
