# Generated by Django 5.2 on 2025-04-21 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_name",
                    models.CharField(max_length=50, unique=True, verbose_name="게임명"),
                ),
                ("original_price", models.IntegerField(default=0, verbose_name="원가")),
                (
                    "discount_price",
                    models.IntegerField(default=0, verbose_name="현재가격"),
                ),
                (
                    "discount_startdate",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="할인시작일",
                    ),
                ),
                (
                    "discount_enddate",
                    models.DateTimeField(blank=True, verbose_name="할인종료일"),
                ),
                (
                    "release_date",
                    models.DateTimeField(blank=True, verbose_name="발매일"),
                ),
                ("maker", models.CharField(max_length=100, verbose_name="개발사")),
                (
                    "player_number",
                    models.CharField(default=1, verbose_name="플레이 인원수"),
                ),
                (
                    "product_type",
                    models.BooleanField(
                        default=False, verbose_name="상품유형(실물여부)"
                    ),
                ),
                (
                    "game_image_url",
                    models.URLField(default="", verbose_name="이미지URL"),
                ),
                (
                    "game_url",
                    models.URLField(default="", max_length=100, verbose_name="URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_name",
                    models.CharField(
                        default="", max_length=50, unique=True, verbose_name="장르명"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="", max_length=50, unique=True, verbose_name="언어"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainpage.game"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainpage.genre"
                    ),
                ),
            ],
            options={
                "db_table": "game_genre",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="genre",
            field=models.ManyToManyField(
                default="",
                through="mainpage.GameGenre",
                to="mainpage.genre",
                verbose_name="장르",
            ),
        ),
        migrations.CreateModel(
            name="GameLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainpage.game"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.language",
                    ),
                ),
            ],
            options={
                "db_table": "game_language",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="game_language",
            field=models.ManyToManyField(
                default="",
                through="mainpage.GameLanguage",
                to="mainpage.language",
                verbose_name="대응언어",
            ),
        ),
    ]
