# Generated by Django 5.2 on 2025-04-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_language",
            field=models.ManyToManyField(
                through="mainpage.GameLanguage",
                to="mainpage.language",
                verbose_name="대응언어",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.ManyToManyField(
                through="mainpage.GameGenre", to="mainpage.genre", verbose_name="장르"
            ),
        ),
    ]
