# Generated by Django 5.2 on 2025-04-22 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_alter_game_game_language_alter_game_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="collect_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="데이터 수집일"
            ),
        ),
    ]
