# Generated by Django 5.2 on 2025-04-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0003_game_collect_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="product_type",
            field=models.CharField(default="", verbose_name="상품유형"),
        ),
    ]
