# Generated by Django 5.2 on 2025-04-22 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_alter_game_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="할인시작일",
            ),
        ),
    ]
