# Generated by Django 5.2 on 2025-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0005_alter_game_discount_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(
                blank=True, default=None, verbose_name="할인종료일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True, default=None, verbose_name="할인시작일"
            ),
        ),
    ]
