# Generated by Django 5.2 on 2025-04-22 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0007_alter_game_collect_date_alter_game_game_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="collect_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="데이터 수집일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(blank=True, verbose_name="할인종료일"),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="할인시작일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_image_url",
            field=models.URLField(default="", verbose_name="이미지URL"),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_language",
            field=models.ManyToManyField(
                through="mainpage.GameLanguage",
                to="mainpage.language",
                verbose_name="대응언어",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_url",
            field=models.URLField(default="", max_length=100, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.ManyToManyField(
                through="mainpage.GameGenre", to="mainpage.genre", verbose_name="장르"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="maker",
            field=models.CharField(max_length=100, verbose_name="개발사"),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_number",
            field=models.CharField(default=1, verbose_name="플레이 인원수"),
        ),
        migrations.AlterField(
            model_name="game",
            name="product_type",
            field=models.CharField(default="", verbose_name="상품유형"),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(blank=True, verbose_name="발매일"),
        ),
    ]
