# Generated by Django 5.2 on 2025-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainpage",
            "0008_alter_game_collect_date_alter_game_discount_enddate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(
                blank=True, default=None, verbose_name="할인종료일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_price",
            field=models.IntegerField(
                default=models.IntegerField(default=0, verbose_name="원가"),
                verbose_name="현재가격",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True, default=None, verbose_name="할인시작일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(blank=True, default=None, verbose_name="발매일"),
        ),
    ]
