# Generated by Django 5.2 on 2025-04-22 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0009_alter_game_discount_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 4, 22, 2, 18, 21, 470402, tzinfo=datetime.timezone.utc
                ),
                verbose_name="할인종료일",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 4, 22, 2, 18, 21, 470380, tzinfo=datetime.timezone.utc
                ),
                verbose_name="할인시작일",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 4, 22, 2, 18, 21, 470447, tzinfo=datetime.timezone.utc
                ),
                verbose_name="발매일",
            ),
        ),
    ]
