# Generated by Django 5.2 on 2025-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0011_alter_game_discount_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="collect_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="데이터 수집일"),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_enddate",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="할인종료일"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="discount_startdate",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="할인시작일"
            ),
        ),
    ]
