# Generated by Django 5.2 on 2025-04-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainpage",
            "0012_alter_game_collect_date_alter_game_discount_enddate_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="player_number",
            new_name="play_number",
        ),
    ]
