# Generated by Django 5.2 on 2025-04-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0013_rename_player_number_game_play_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genre",
            new_name="Genres",
        ),
        migrations.RenameModel(
            old_name="Language",
            new_name="Languages",
        ),
    ]
